import numpy as np
import sys
import smtplib
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
import base64
import ssl
import getpass
import os

import pandas as pd

################################################################################
# Reference
# https://julien.danjou.info/sending-emails-in-python-tutorial-code-examples/
# https://realpython.com/python-send-email/
################################################################################

########################################################################

################################################################################
def write_and_send_email(rec_email, title, name, body_text):

    message = MIMEMultipart("alternative")
    message["Subject"] = "CMS Summer Internship Program for Underrepresented Minority Undergraduate Students"
    message["From"] = sender_email
    #message["To"] = rec_email
    message["To"] = "matthew.bellis@gmail.com"

    text = f"{title} {name},\n\n"
    text += body_text

    part1 = MIMEText(text, "plain")

    message.attach(part1)

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(sender_email, password)
        # UNCOMMENT THIS WHEN SENDING FOR REAL
        # FOR TESTING
        receiver_email = rec_email
        #receiver_email = "matthew.bellis@gmail.com"
        server.sendmail(sender_email, receiver_email, message.as_string())



################################################################################

################################################################################
infilename = sys.argv[1]
bodytextfile = sys.argv[2]
################################################################################

########################################################################
login = "1a2b3c4d5e6f7g" # paste your login generated by Mailtrap
password = "1a2b3c4d5e6f7g" # paste your password generated by Mailtrap
sender_email = "matthew.bellis@gmail.com"
# FOR TESTING
receiver_email = "mbellis@siena.edu"
port = 465
#password = getpass.getpass("Your password: ")

context = ssl.create_default_context()

#'''
with smtplib.SMTP_SSL("smtp.gmail.com", port, context=context) as server:
    server.login(sender_email, password)
#'''

df = pd.read_csv(infilename)
df

body_text = ""
for line in open(bodytextfile,'r'):
    body_text += line

print(body_text)

df = df[0:4]

ncontacts = len(df)

for i in range(ncontacts):

    rec_email = df.iloc[i]['Chair E-mail']
    title = df.iloc[i]['Title1'] 
    name = df.iloc[i]['Chairperson'] 

    print(rec_email,title,name)

    #write_and_send_email(rec_email, title, name, body_text)
    write_and_send_email("mbellis@siena.edu", title, name, body_text)























