import os 

env = Environment()

# Grab my local environment variable PATH so I can find nvcc
env = Environment(ENV = {'PATH' : os.environ['PATH']})

env['CC'] = ['nvcc']

env.Program(target='hello_world_shared_0', source=['hello_world_shared_0.cu'])
env.Program(target='dobbs_example', source=['dobbs_example.cu'])
env.Program(target='hello_world_hist_shared_0', source=['hello_world_hist_shared_0.cu'])


