eval `dircolors -c $HOME/.dir_colors`

alias ls 	'ls --color=auto'
#alias gmake	'make'
#eval `dircolors $HOME/.dir_colors`

#alias jupyter /opt/anaconda3/bin/jupyter-notebook

limit coredumpsize 102400 # limit size to 100M


setenv MYSQL_INCLUDE_PATH /usr/include/mysql
setenv MYSQL_LIB_PATH /usr/lib/mysql
setenv CLASTOOL `pwd`

setenv LD_LIBRARY_PATH 	/usr/lib/root

setenv PATH ":./home/bellis/.local/bin/:$HOME/bin:$HOME/bin_scripts:${PATH}:"

## Needed to add this for latex2html to work...oh well.
setenv RGBDEF /etc/X11/rgb.txt

#setenv PYTHONPATH /opt/anaconda3/:/opt/anaconda3/lib/:/usr/local:/usr/local/lib//usr/local/lib/root/:${HOME}/libs/:/usr/lib/x86_64-linux-gnu:/home/bellis/root/lib/
#setenv PYTHONPATH /opt/anaconda3/:/usr/local/lib/root:/usr/local:/usr/local/lib/:/usr/local/lib/root/:/usr/lib/x86_64-linux-gnu
#setenv PYTHONPATH /usr/local/lib/root:/usr/local:/usr/local/lib/:/usr/local/lib/root/:/usr/lib/x86_64-linux-gnu
# NORMAL!!!!
setenv PYTHONPATH /opt/anaconda3/:/usr/local/lib/root:/usr/local:/usr/local/lib/:/usr/local/lib/root/:/usr/lib/x86_64-linux-gnu
#setenv PYTHONPATH /opt/anaconda/:/usr/local/lib/root:/usr/local:/usr/local/lib/:/usr/local/lib/root/:/usr/lib/x86_64-linux-gnu

# MADGRAPH!!!
#setenv PYTHONPATH /usr/local/lib/root:/usr/local:/usr/local/lib/:/usr/local/lib/root/:/usr/lib/x86_64-linux-gnu


setenv SVN_EDITOR vi
setenv EDITOR vi

# CUDA stuff
#setenv PATH ${PATH}:/usr/local/cuda/bin
#setenv PATH ${PATH}:/usr/local/cuda-6.5/bin
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/usr/local/cuda-6.5/lib64

###### G4 stuff
#source /home/bellis/src/geant4/geant4.9.0.p01/env.csh
#setenv G4WORKDIR /home/bellis/g4work
#setenv LD_LIBRARY_PATH /home/bellis/src/CLHEP/2.0.3.2/CLHEP/lib:$LD_LIBRARY_PATH

# For my beamer stuff
setenv MY_BEAMER_THEMES ${HOME}/Talks/my_beamer_themes

# For CUDA
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/usr/lib/x86_64-linux-gnu/
#setenv CUDA_INSTALL_PATH /usr/
setenv CUDA_HOME /usr/local/cuda-6.5/
#setenv CUDA_INSTALL_PATH /usr

# For PyMinuit
#setenv LD_LIBRARY_PATH .:/home/bellis/python_packages/Minuit-1_7_9/src/.libs:${LD_LIBRARY_PATH}
#setenv PYTHONPATH /your/home/lib/python:${PYTHONPATH}

# For Java
#setenv PATH /opt/anaconda3/bin:${PATH}:/usr/local/java/bin/
#setenv PATH ${PATH}:/usr/local/java/bin/
# NORMAL!!!!!!!!!!!!!!!!!!!!!
setenv PATH /opt/anaconda3/bin:${PATH}:/usr/local/java/bin/
#setenv PATH /opt/anaconda/bin:${PATH}:/usr/local/java/bin/

#setenv LD_LIBRARY_PATH /opt/anaconda3/lib/:${LD_LIBRARY_PATH}:/usr/lib/i386-linux-gnu/
#setenv LD_LIBRARY_PATH /usr/lib/i386-linux-gnu/
# MADGRAPH!!!!!!!!!!
#setenv PATH ${PATH}:/usr/local/java/bin/

#setenv LD_LIBRARY_PATH ${HOME}/anaconda3/:${HOME}/anaconda3/lib:${LD_LIBRARY_PATH}:/usr/lib/i386-linux-gnu/
#setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/usr/lib/i386-linux-gnu/
#setenv LD_LIBRARY_PATH /opt/anaconda3/lib/:${LD_LIBRARY_PATH}:/usr/lib/i386-linux-gnu/
#setenv LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu/:/opt/anaconda3/lib/:/opt/anaconda3/
#setenv LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu/
#setenv LD_LIBRARY_PATH /opt/anaconda3/lib/:/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu/
setenv LD_LIBRARY_PATH #/opt/anaconda3/lib/:/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu/
#setenv LD_LIBRARY_PATH /opt/anaconda3/lib/:/opt/anaconda3/:${LD_LIBRARY_PATH}:/usr/lib/i386-linux-gnu/
#setenv LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu/:/opt/anaconda3/lib/
#setenv LD_LIBRARY_PATH #/usr/lib/i386-linux-gnu/:/usr/lib/x86_64-linux-gnu/
#setenv LD_LIBRARY_PATH /opt/anaconda3/lib/

setenv S2PLOT_PRCDRIVER s2prcwriter
setenv S2PATH /home/bellis/s2plot
setenv S2ARCH linux-gnu-x86_64
setenv S2PLOT_LATEXBIN /usr/bin/

setenv PRINTER RB131

#source /usr/local/bin/geant4.csh

setenv QT_PLUGIN_PATH /opt/anaconda2/plugins/


# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause

alias __mamba_exe '"/home/bellis/bin/micromamba" "\!*"'

alias __mamba_hashr 'rehash'

alias __mamba_xctivate '
    set ask_conda="`(setenv prompt "${prompt}"; __mamba_exe shell "\!*" --shell csh)`"
    if ("${status}" != 0) then
        return
     endif
         eval "${ask_conda}"
     __mamba_hashr
'

alias micromamba '
    switch ("${1}")
        case activate | reactivate | deactivate:
            __mamba_xctivate "\!*"
            breaksw
        case install | update | upgrade | remove | uninstall:
            __mamba_exe "\!*"
            if ("${status}" != 0) then
                return
             endif
            __mamba_xctivate reactivate
            breaksw
        case self-update:
            __mamba_exe "\!*"
            if ("${status}" != 0) then
                return
             endif
             if (-f "/home/bellis/bin/micromamba.bkup") then
                rm -f "/home/bellis/bin/micromamba.bkup"
             endif
            breaksw
        default:
            __mamba_exe "\!*"
            breaksw
    endsw
'

if (! $?CONDA_SHLVL) then
    setenv CONDA_SHLVL 0
    # In dev-mode MAMBA_EXE is python.exe and on Windows
    # it is in a different relative location to condabin.
    if ($?_CE_CONDA && $?WINDIR) then
        setenv PATH "${MAMBA_ROOT_PREFIX}/condabin:${PATH}"
    else
        setenv PATH "${MAMBA_ROOT_PREFIX}/condabin:${PATH}"
    endif

    # We're not allowing PS1 to be unbound. It must at least be set.
    # However, we're not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if (! $?PS1) then
        setenv PS1 ''
    endif
endif


