" Vim
" " An example for a vimrc file.
" "
" " To use it, copy it to
" "     for Unix and OS/2:  ~/.vimrc
" "             for Amiga:  s:.vimrc
" "  for MS-DOS and Win32:  $VIM\_vimrc
"
 set nocompatible        " Use Vim defaults (much better!)
 set bs=2                " allow backspacing over everything in insert mode
 set ai                  " always set autoindenting on
" set backup              " keep a backup file
 set viminfo='20,\"50    " read/write a .viminfo file, don't store more
                         " than 50 lines of registers

" My keybindings
ab myitem \begin{itemize}\item XXX\end{itemize}
ab myframe \frame{\frametitle{XXX}}

filetype indent on
"colorscheme morning
colorscheme elflord
"colorscheme pablo
set cindent
set cindent shiftwidth=4
set autoindent shiftwidth=4
set cinoptions+={
set expandtab

set tabstop=4
" set shiftwidth=2
set nowrapscan
set ignorecase
" In text files, always limit the width of text to 78 characters
autocmd BufRead *.txt set tw=78 

" Remember last edit
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") |
                         \ exe "normal g'\"" | endif

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let & guioptions = substitute(& guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
 map Q gq

 " Switch syntax highlighting on, when the terminal has colors
 " Also switch on highlighting the last used search pattern.
" if & t_Co > 2 || has("gui_running")
" if & t_Co > 2 
   syntax on
   set hlsearch
   highlight Search term=reverse  ctermbg=0 ctermfg=2 guibg=black guifg=white
"	 highlight Search term=reverse  ctermbg=4 ctermfg=3 guibg=white guifg=black
"	 highlight Search term=reverse  ctermbg=white ctermfg=black guibg=white guifg=black
" endif

" Commented this to remove that stuff at beginning that I 
" needed to hit space to get past.
"augroup cprog
" Remove all cprog autocommands
"au!

" When starting to edit a file:
"   For *.c and *.h files set formatting of comments and set C-indenting on.
"   For other files switch it off.
"   Don't change the order, it's important that the line with * comes first.
"autocmd BufRead *       set formatoptions=tcql nocindent comments
"autocmd BufRead *.c,*.cc,*.C,*.cxx,*.h set formatoptions=croql cindent comments=sr:/*,mb:*,el:*/,://
"augroup END

"finish " Maybe this removes the weird start 



