wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA/DAMA_08_Savage_3sig_noCH.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA/DAMA_08_Savage_3sig_noCH.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA_08_Savage_5sig.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA/DAMA_08_Savage_5sig.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMSII_LowThresh_Ge_SI_elastic.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA/DAMA_I_from_Xenon100_2011.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA_dam90_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA/DAMA_dam90_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA/DAMA_dam99_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/EdelweissII_Dec09.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/EDELWEISS/EdelweissII_Dec09.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_0Ge_2Si_p50_100Vb_8Bv3D.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_4Ge_0Si_p50_100Vb_8Bv3D.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_4Ge_2Si_p50_100Vb_8Bv3D.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/SuperCDMS_SNOLAB_100kg_May2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/EdelweissII_Final_SI_elastic.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_SNOLAB_100kg_May2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_0Ge_36Si_p50_q100_8Bv3D.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_108Ge_0Si_p50_q100_8Bv3D.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_108Ge_0Si_p50_q100_8Bv3D.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_108Ge_36Si_p50_q100_8Bv3D.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/SuperCDMS_SNOLAB_LT_2013_SI_proj.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_SNOLAB_LT_2013_SI_proj.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/SuperCDMS_Soudan_15kg_May2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_Soudan_15kg_May2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/SuperCDMS_Soudan_9kg_2012_SI_proj.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_Soudan_9kg_2012_SI_proj.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/EDELWEISS/EdelweissII_Final_SI_elastic.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/SuperCDMS_Soudan_LT_2013_SI_proj.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_Soudan_LT_2013_SI_proj.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/XENON/XENON1T_proj_2013.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/HooperKelsoBuckley_68CL_11105338.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMSlite_Soudan_170eVee_SI_proj.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/Hooper_PRD_82_123509_2010_DAMA_CoGeNT_Co90.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/MALBEK_2013_SI_prelim.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/MALBEK_wavelet_2013_SI_prelim.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Other/NeutrinoBackground_Billardetal2013.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/ROSEBUD_01_si.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/SIMPLE_2012_SI.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS_091217_Ge_c58.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_091217_Ge_c58.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS_091217_Ge_comb.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_091217_Ge_comb.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/TEXONO_Dec2007.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/Trotta_flatpriors_Xenon100_68CL.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/UK_NAIAD_2005.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/WARP_0701286_40kev.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/WARP_0701286_55kev.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/XENON/XENON100_IDM2012.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/XENON100_SI_2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS_Edelweiss_PRD2011.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_Edelweiss_PRD2011.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS_SUFLowThresh_PRD122010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/XENON10_SI_PRCmod.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/XENON10_SI_PRL.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/XMASS13.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/XENON/Xenon100_2011.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/XENON/Xenon10_S2only_2011.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_Si_c34_SI_UL.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_Si_c34c58_SI_CombUL.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_Si_c58_SI_68CL.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_Si_c58_SI_90CL.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_Si_c58_SI_95CL.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_Si_c58_SI_99CL.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMS_Si_c58_SI_UpperLim.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/CDMSlite_Run1_2013_SI_official.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/COUPP/COUPP_2012.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CRESST/CRESST-II_2009.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CRESST/CRESSTII_Sept2011_allowed_1sig.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CRESST/CRESSTII_Sept2011_allowed_2sig.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/IceCube_SI_hard_2009.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/IceCube_SI_soft_2009.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/KIMS_2007_SI.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGENT_March2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/LUX2013.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNT/CoGENT_March2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNTDAMA_comb90_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNT/CoGeNTDAMA_comb90_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNTDAMA_comb99_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNT/CoGeNTDAMA_comb99_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNT/CoGeNT_Co90_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNT/CoGeNT_Co99_Hooper_PRD_82_123509_2010_DAMA_CoGeNT.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNT/CoGeNT_PRL107_2011_annmod_roi.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNT_compat_thy_2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CoGeNT/CoGeNT_compat_thy_2010.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/ZEPLINIII_2011_SI.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/edw_lim_2012.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/EDELWEISS/edw_lim_2012.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Thy/Battaglia_pMSSM_arxiv12114004.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Thy/CMSSM_mx_sigsip_68cl.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Thy/CMSSM_mx_sigsip_95cl.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/CDMS/SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_108Ge_0Si_p50_q100_8Bv3D.limit
wget http://dendera.berkeley.edu/plotter/limitdata/SI_Expt/DAMA/DAMA_08_Savage_3sig_noCH.limit
