def set_initial_values(pars_dict):

    pars_dict["frac_12_3_x_offpeak"].setVal(0.99)
    pars_dict["frac_12_3_x_offpeak"].setConstant(True)
    #
    pars_dict["frac_12_x_offpeak"].setVal(0.99)
    pars_dict["frac_12_x_offpeak"].setConstant(True)
    #
    pars_dict["gauss_conv_x_offpeak_3"].setVal(0.99)
    pars_dict["gauss_conv_x_offpeak_3"].setConstant(True)
    #
    pars_dict["mean_x_offpeak_0"].setVal(0.99)
    pars_dict["mean_x_offpeak_0"].setConstant(True)
    #
    pars_dict["mean_x_offpeak_1"].setVal(0.99)
    pars_dict["mean_x_offpeak_1"].setConstant(True)
    #
    pars_dict["mean_x_offpeak_2"].setVal(0.99)
    pars_dict["mean_x_offpeak_2"].setConstant(True)
    #
    pars_dict["mean_x_offpeak_3"].setVal(0.99)
    pars_dict["mean_x_offpeak_3"].setConstant(True)
    #
    pars_dict["sigma_x_offpeak_0"].setVal(0.99)
    pars_dict["sigma_x_offpeak_0"].setConstant(True)
    #
    pars_dict["sigma_x_offpeak_1"].setVal(0.99)
    pars_dict["sigma_x_offpeak_1"].setConstant(True)
    #
    pars_dict["sigma_x_offpeak_2"].setVal(0.99)
    pars_dict["sigma_x_offpeak_2"].setConstant(True)
    #
    pars_dict["sigma_x_offpeak_3"].setVal(0.99)
    pars_dict["sigma_x_offpeak_3"].setConstant(True)
    #
