import os 

env = Environment()

# Grab my local environment variable PATH so I can find nvcc
env = Environment(ENV = {'PATH' : os.environ['PATH']})

env['CC'] = ['nvcc']

env.Program(target='parallel_reduction', source=['parallel_reduction.cu'])


