# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop EdelweissII_Dec09.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'EdelweissII_Dec09.limit'
file_version = 'v1'
file_status = 'public'
data_label = 'Edelweiss II first result, 144 kg-days interleaved Ge'
data_comment = 'Sigma for SI coupled WIMP, normalized to X-nucleon'
data_reference = '<a href ="http://arxiv.org/abs/0912.0805"> arXiv:0912.0805 </a>'
private_comment = 'Supplied by Jules Gascon, 7Dec2009'
data_typeoflimit = ['90\n % CL exclusion plot', 'SI-Exp']
formdefault_checked = ''
formdefault_color = 'DkR'
formdefault_style = 'Line'
data_units = ['GeV', 'cm^2']
data_values = np.array([12.0, 0.00069423602, 14.0, 4.62301e-05, 16.0, 1.08849e-05, 18.0, 3.8456601e-06, 20.0, 1.82085e-06, 22.0, 1.04566e-06, 24.0, 6.8548002e-07, 26.0, 4.9389899e-07, 28.0, 3.7807399e-07, 30.0, 3.0581199e-07, 35.0, 2.0895401e-07, 40.0, 1.63715e-07, 45.0, 1.39443e-07, 50.0, 1.25111e-07, 55.0, 1.15874e-07, 60.0, 1.10146e-07, 65.0, 1.06799e-07, 70.0, 1.04754e-07, 75.0, 1.03609e-07, 80.0, 1.03092e-07, 85.0, 1.03088e-07, 90.0, 1.03425e-07, 95.0, 1.04544e-07, 100.0, 1.05397e-07, 120.0, 1.11824e-07, 140.0, 1.1974799e-07, 160.0, 1.29013e-07, 180.0, 1.3819199e-07, 200.0, 1.48285e-07, 220.0, 1.5792099e-07, 240.0, 1.68536e-07, 260.0, 1.79129e-07, 280.0, 1.8982099e-07, 300.0, 2.00589e-07, 500.0, 3.0893901e-07, 1000.0, 5.8357102e-07]).reshape(1, -1)
data_values_rescale = np.array([1, 1e-36]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
