# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop Hooper_PRD_82_123509_2010_DAMA_CoGeNT_Co90.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

