# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop IceCube_SI_soft_2009.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'IceCube_SI_soft_2009.limit'
file_version = 'v1'
file_status = 'public'
data_label = 'IceCube 2009 indirect SI (assuming annihilation to b-bbar)'
data_comment = 'Spin-independent cross section'
data_reference = 'Abbasi et al., Phys. Rev. Lett. 102, 201302 (2009), <a href = "http://arxiv.org/abs/0902.2460">arXiv:0902.2460</a>'
private_comment = 'Data for "soft" channel from Table 1'
data_typeoflimit = ['Exclusion Plot', 'SI-Exp']
formdefault_checked = ''
formdefault_color = 'Red'
formdefault_style = 'Dash'
data_units = ['GeV', 'cm^2']
data_values = np.array([500, 2.5e-41, 1000, 1.8e-41, 3000, 5.3e-41, 5000, 1.1e-40]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
