# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop CoGENT_March2010.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'our_cogent'
file_status = 'public'
data_label = 'CoGeNT (this analysis) PRELIMINARY exclusion limits, April 2014'
data_comment = ''
data_reference = ''
private_comment = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Exp']
formdefault_checked = ''
formdefault_color = 'G60'
formdefault_style = 'Line'
data_units = ['GeV', 'cm^2']
data_values = np.array([6 , 6e-40,
    8 , 4e-42,
    10 , 4e-42,
    15 , 4e-42,
    20 , 4e-42,
    30 , 4e-42,
    ]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 230
