# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop ROSEBUD_01_si.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'ROSEBUD_01_si.limit'
file_version = 'v1'
file_status = 'public'
data_label = 'ROSEBUD 2001 Exclusion Limit'
data_comment = 'Cross-section data for simple scalar interaction normalised single nucleon'
data_reference = 'S. Cebrian et al., <a href="references/ROSEBUD_astroph0004292.pdf">astro-ph/0004292</a>'
private_comment = ''
data_version = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Exp']
formdefault_checked = ''
formdefault_color = 'Grn'
formdefault_style = 'Line'
data_units = ['GeV', 'cm^2']
data_values = np.array([6.515, 8.426e-37, 8.101, 4.641e-37, 11.56, 2.134e-37, 16.99, 9.998e-38, 25.34, 6.144e-38, 41.83, 4.869e-38, 56.75, 4.374e-38, 98.56, 5.354e-38, 155.8, 7.301e-38, 286.7, 1.173e-37, 453.1, 1.783e-37, 896.8, 3.252e-37]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
