# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_4Ge_2Si_p50_100Vb_8Bv3D.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_4Ge_2Si_p50_100Vb_8Bv3D.limit'
file_status = 'public'
data_label = 'SuperCDMS-lite (SNOLAB), 4 Ge + 2 Si, SI (proj)'
data_comment = 'Cross-section data for scalar interaction normalised to nucleon; SCDMS LITE 4Ge (100V) + 2Si (150V)'
data_reference = 'M. Pyle, private communication (9/20/2013)'
private_comment = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Proj']
formdefault_checked = 'checked'
formdefault_color = 'Blk'
formdefault_style = 'Dot'
data_units = ['GeV', 'cm^2']
data_values = np.array([0.25, 0, 0.292, 6.0158e-39, 0.341, 1.72046e-41, 0.398, 2.30123e-42, 0.465, 6.83037e-43, 0.543, 3.0444e-43, 0.634, 1.77917e-43, 0.74, 1.42219e-43, 0.865, 1.84717e-43, 1.01, 1.70848e-43, 1.179, 8.684145e-44, 1.377, 4.93978e-44, 1.608, 3.78953e-44, 1.878, 3.04617e-44, 2.193, 2.574835e-44, 2.561, 2.47337e-44, 2.991, 2.454895e-44, 3.493, 2.38207e-44, 4.079, 2.31963e-44, 4.764, 2.259805e-44, 5.563, 2.46733e-44, 6.496, 2.55376e-44, 7.586, 2.757475e-44, 8.859, 3.074425e-44, 10.346, 3.3163e-44, 12.082, 3.675835e-44, 14.109, 4.12085e-44, 16.477, 4.6621e-44, 19.242, 5.30807e-44, 22.47, 6.079635e-44, 26.241, 7.013115e-44, 30.644, 7.97355e-44, 35.786, 9.117005e-44, 41.791, 1.05713e-43, 48.803, 1.222785e-43, 56.993, 1.32442e-43, 66.556, 1.257035e-43, 77.724, 1.239575e-43, 90.766, 1.26734e-43, 105.996, 1.33328e-43, 123.782, 1.433455e-43, 144.553, 1.56686e-43, 168.808, 1.734585e-43, 197.134, 1.939015e-43, 230.213, 2.18541e-43, 268.843, 2.47898e-43, 313.954, 2.826365e-43, 366.635, 3.235745e-43, 428.156, 3.716885e-43, 500, 4.281205e-43]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
