# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_0Ge_2Si_p50_100Vb_8Bv3D.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_0Ge_2Si_p50_100Vb_8Bv3D.limit'
file_status = 'public'
data_label = 'SuperCDMS-lite (SNOLAB), 0 Ge + 2 Si, SI (proj)'
data_comment = 'Cross-section data for scalar interaction normalised to nucleon; SCDMS LITE 0Ge (100V) + 2Si (150V)'
data_reference = 'M. Pyle, private communication (9/20/2013)'
private_comment = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Proj']
formdefault_checked = 'checked'
formdefault_color = 'Blk'
formdefault_style = 'Dot'
data_units = ['GeV', 'cm^2']
data_values = np.array([0.25, 0, 0.292, 6.0158e-39, 0.341, 1.72046e-41, 0.398, 2.30123e-42, 0.465, 6.83037e-43, 0.543, 3.0464e-43, 0.634, 1.79215e-43, 0.74, 1.319355e-43, 0.865, 1.070105e-43, 1.01, 1.01253e-43, 1.179, 9.55028e-44, 1.377, 9.73761e-44, 1.608, 1.04787e-43, 1.878, 1.0858e-43, 2.193, 1.25392e-43, 2.561, 1.350995e-43, 2.991, 1.58329e-43, 3.493, 1.69296e-43, 4.079, 1.897715e-43, 4.764, 2.16878e-43, 5.563, 2.454695e-43, 6.496, 2.847695e-43, 7.586, 3.33421e-43, 8.859, 3.829705e-43, 10.346, 4.438635e-43, 12.082, 5.23238e-43, 14.109, 6.26022e-43, 16.477, 7.26852e-43, 19.242, 8.33169e-43, 22.47, 9.81137e-43, 26.241, 1.122995e-42, 30.644, 1.288875e-42, 35.786, 1.48824e-42, 41.791, 1.718325e-42, 48.803, 1.992775e-42, 56.993, 2.31828e-42, 66.556, 2.685205e-42, 77.724, 3.102905e-42, 90.766, 3.46595e-42, 105.996, 3.748825e-42, 123.782, 4.12054e-42, 144.553, 4.558385e-42, 168.808, 5.07978e-42, 197.134, 5.705455e-42, 230.213, 6.449235e-42, 268.843, 7.32838e-42, 313.954, 8.364615e-42, 366.635, 9.58174e-42, 428.156, 1.10089e-41, 500, 1.26804e-41]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
