# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_4Ge_0Si_p50_100Vb_8Bv3D.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'SCDMSLITE_SNOLAB_CLWIMP_SNOMASS10_LITE_4Ge_0Si_p50_100Vb_8Bv3D.limit'
file_status = 'public'
data_label = 'SuperCDMS-lite (SNOLAB), 4 Ge + 0 Si, SI (proj)'
data_comment = 'Cross-section data for scalar interaction normalised to nucleon; SCDMS LITE 4Ge (100V) + 0Si (150V)'
data_reference = 'M. Pyle, private communication (9/20/2013)'
private_comment = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Proj']
formdefault_checked = 'checked'
formdefault_color = 'Blk'
formdefault_style = 'Dot'
data_units = ['GeV', 'cm^2']
data_values = np.array([0.25, 0, 0.291949655934, 0, 0.340938406401, 0, 0.398147401774, 0, 0.464955987837, 0, 0.542974962694, 0, 0.634, 8.63976e-41, 0.74, 1.169055e-42, 0.865, 2.51201e-43, 1.01, 1.034965e-43, 1.179, 5.94805e-44, 1.377, 3.52473e-44, 1.608, 2.95124e-44, 1.878, 2.80591e-44, 2.193, 2.58237e-44, 2.561, 2.368465e-44, 2.991, 2.072695e-44, 3.493, 2.15239e-44, 4.079, 2.07033e-44, 4.764, 2.13421e-44, 5.563, 2.3681e-44, 6.496, 2.59968e-44, 7.586, 2.75666e-44, 8.859, 3.02991e-44, 10.346, 3.327155e-44, 12.082, 3.703515e-44, 14.109, 4.151e-44, 16.477, 4.57942e-44, 19.242, 5.11283e-44, 22.47, 5.866395e-44, 26.241, 6.77964e-44, 30.644, 7.85217e-44, 35.786, 9.056985e-44, 41.791, 1.04641e-43, 48.803, 1.216855e-43, 56.993, 1.35385e-43, 66.556, 1.29044e-43, 77.724, 1.26947e-43, 90.766, 1.296835e-43, 105.996, 1.36353e-43, 123.782, 1.465395e-43, 144.553, 1.60133e-43, 168.808, 1.77215e-43, 197.134, 1.9809e-43, 230.213, 2.232605e-43, 268.843, 2.53246e-43, 313.954, 2.88734e-43, 366.635, 3.305645e-43, 428.156, 3.797235e-43, 500, 4.373845e-43]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
