# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop SuperCDMS_Soudan_15kg_May2010.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'SuperCDMS_Soudan_15kg_May2010.limit'
file_status = 'public'
data_label = 'SuperCDMS - 15 kg at Soudan'
data_comment = 'Cross-section data for scalar interaction normalised to nucleon'
data_reference = 'SuperCDMS Proposal'
private_comment = 'SuperCDMS Proposal 2008'
data_typeoflimit = ['Exclusion Plot', 'SI-Proj']
formdefault_checked = 'checked'
formdefault_color = 'Blk'
formdefault_style = 'Dot'
data_units = ['GeV', 'cm^2']
data_values = np.array([8.203, 4.926e-41, 8.62, 8.644e-42, 9.057, 3.256e-42, 9.517, 1.594e-42, 10.0, 8.477e-43, 11.22, 4.642e-43, 12.589, 1.969e-43, 14.125, 1.001e-43, 15.849, 5.775e-44, 19.953, 2.391e-44, 25.119, 1.158e-44, 31.623, 7.172e-45, 39.811, 5.556e-45, 50.119, 4.833e-45, 63.096, 4.75e-45, 79.433, 5.042e-45, 100.0, 5.673e-45, 125.893, 6.491e-45, 158.489, 7.73e-45, 199.526, 9.375e-45, 251.189, 1.146e-44, 316.228, 1.399e-44, 398.107, 1.738e-44, 501.187, 2.156e-44, 630.957, 2.679e-44, 794.328, 3.344e-44, 1000.0, 4.185e-44, 1258.925, 5.248e-44, 1584.893, 6.584e-44, 1995.262, 8.262e-44, 2511.886, 1.037e-43, 3162.278, 1.304e-43, 3981.072, 1.639e-43, 5011.872, 2.061e-43, 6309.573, 2.593e-43, 7943.282, 3.262e-43, 10000.0, 4.104e-43]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
