# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_0Ge_36Si_p50_q100_8Bv3D.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_0Ge_36Si_p50_q100_8Bv3D.limit'
file_status = 'public'
data_label = 'SuperCDMS SNOLAB, 0 Ge + 36Si, SI (proj)'
data_comment = 'Cross-section data for scalar interaction normalised to nucleon; Standard Running 0Ge 36Si'
data_reference = 'M. Pyle, private communication (9/20/2013)'
private_comment = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Proj']
formdefault_checked = 'checked'
formdefault_color = 'Blk'
formdefault_style = 'Dot'
data_units = ['GeV', 'cm^2']
data_values = np.array([0.25, 0, 0.291949655934, 0, 0.340938406401, 0, 0.398147401774, 0, 0.464955987837, 0, 0.543, 6.911905e-39, 0.634, 1.57726e-41, 0.74, 2.966155e-42, 0.865, 1.14502e-42, 1.01, 6.445325e-43, 1.179, 4.390525e-43, 1.377, 3.74207e-43, 1.608, 3.430785e-43, 1.878, 3.095435e-43, 2.193, 2.268185e-43, 2.561, 1.241785e-43, 2.991, 7.124175e-44, 3.493, 3.744555e-44, 4.079, 2.5306e-44, 4.764, 1.812715e-44, 5.563, 1.40545e-44, 6.496, 1.10406e-44, 7.586, 8.809045e-45, 8.859, 7.483475e-45, 10.346, 6.4328e-45, 12.082, 5.167265e-45, 14.109, 4.34058e-45, 16.477, 3.68194e-45, 19.242, 3.239635e-45, 22.47, 2.88018e-45, 26.241, 2.763e-45, 30.644, 2.727605e-45, 35.786, 2.717835e-45, 41.791, 2.787835e-45, 48.803, 2.742195e-45, 56.993, 2.932105e-45, 66.556, 3.183775e-45, 77.724, 3.251965e-45, 90.766, 3.61233e-45, 105.996, 4.04816e-45, 123.782, 4.568825e-45, 144.553, 5.185115e-45, 168.808, 5.911835e-45, 197.134, 6.76826e-45, 230.213, 7.773285e-45, 268.843, 8.9511e-45, 313.954, 1.033e-44, 366.635, 1.19421e-44, 428.156, 1.38283e-44, 500, 1.60333e-44]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
