# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_108Ge_36Si_p50_q100_8Bv3D.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_108Ge_36Si_p50_q100_88v3D.limit'
file_status = 'public'
data_label = 'SuperCDMS SNOLAB, 108 Ge + 36 Si, SI (proj)'
data_comment = 'Cross-section data for scalar interaction normalised to nucleon; Standard Running: 108Ge+36 Si'
data_reference = 'M. Pyle, private communication (9/20/2013)'
private_comment = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Proj']
formdefault_checked = 'checked'
formdefault_color = 'Blk'
formdefault_style = 'Dot'
data_units = ['GeV', 'cm^2']
data_values = np.array([0.25, 0, 0.291949655934, 0, 0.340938406401, 0, 0.398147401774, 0, 0.464955987837, 0, 0.543, 8.66647e-39, 0.634, 1.764315e-41, 0.74, 3.114945e-42, 0.865, 1.153345e-42, 1.01, 6.381635e-43, 1.179, 4.52474e-43, 1.377, 3.804185e-43, 1.608, 3.4875e-43, 1.878, 3.352125e-43, 2.193, 1.71771e-43, 2.561, 1.04011e-43, 2.991, 7.70523e-44, 3.493, 5.29243e-44, 4.079, 2.542825e-44, 4.764, 1.381175e-44, 5.563, 8.830275e-45, 6.496, 5.69351e-45, 7.586, 3.30151e-45, 8.859, 1.730175e-45, 10.346, 7.51231e-46, 12.082, 4.20456e-46, 14.109, 2.66271e-46, 16.477, 1.808425e-46, 19.242, 1.303255e-46, 22.47, 1.0037625e-46, 26.241, 8.60751e-47, 30.644, 7.21054e-47, 35.786, 6.688845e-47, 41.791, 6.47619e-47, 48.803, 5.666115e-47, 56.993, 5.84826e-47, 66.556, 6.190165e-47, 77.724, 6.685905e-47, 90.766, 7.338055e-47, 105.996, 8.154205e-47, 123.782, 9.14801e-47, 144.553, 1.034435e-46, 168.808, 1.176925e-46, 197.134, 1.345465e-46, 230.213, 1.54444e-46, 268.843, 1.77781e-46, 313.954, 2.051335e-46, 366.635, 2.371945e-46, 428.156, 2.747295e-46, 500, 3.186335e-46]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
