# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_108Ge_0Si_p50_q100_8Bv3D.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'SuperCDMS_SNOLAB_CLWIMP_SNOMASS10_YPQFV_108Ge_0Si_p50_q100_8Bv3D.limit'
file_status = 'public'
data_label = 'SuperCDMS SNOLAB, 108 Ge + 0 Si, SI (proj)'
data_comment = 'Cross-section data for scalar interaction normalised to nucleon; Standard Running 108Ge 0 Si'
data_reference = 'M. Pyle, private communication (9/20/2013)'
private_comment = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Proj']
formdefault_checked = 'checked'
formdefault_color = 'Blk'
formdefault_style = 'Dot'
data_units = ['GeV', 'cm^2']
data_values = np.array([0.25, 0, 0.291949655934, 0, 0.340938406401, 0, 0.398147401774, 0, 0.464955987837, 0, 0.542974962694, 0, 0.634085414158, 0, 0.740484073986, 0, 0.864736282501, 0, 1.0098378406, 0, 1.17928724045, 0, 1.377, 1.370425e-41, 1.608, 1.302705e-42, 1.878, 3.72753e-43, 2.193, 1.70595e-43, 2.561, 1.048365e-43, 2.991, 7.61826e-44, 3.493, 5.24079e-44, 4.079, 2.50455e-44, 4.764, 1.36111e-44, 5.563, 8.798465e-45, 6.496, 5.71094e-45, 7.586, 3.44984e-45, 8.859, 1.79807e-45, 10.346, 8.428015e-46, 12.082, 4.610135e-46, 14.109, 2.81042e-46, 16.477, 1.92401e-46, 19.242, 1.362065e-46, 22.47, 1.0411e-46, 26.241, 8.747225e-47, 30.644, 7.23259e-47, 35.786, 6.70508e-47, 41.791, 6.50828e-47, 48.803, 5.688965e-47, 56.993, 5.872755e-47, 66.556, 6.219945e-47, 77.724, 6.721445e-47, 90.766, 7.37884e-47, 105.996, 8.20297e-47, 123.782, 9.205445e-47, 144.553, 1.041315e-46, 168.808, 1.185575e-46, 197.134, 1.356815e-46, 230.213, 1.558705e-46, 268.843, 1.795855e-46, 313.954, 2.073935e-46, 366.635, 2.39963e-46, 428.156, 2.78077e-46, 500, 3.22653e-46]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
