# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop SuperCDMS_Soudan_LT_2013_SI_proj.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'SuperCDMS_Soudan_LT_2013_SI_proj.limit'
file_status = 'public'
data_label = 'SuperCDMS Soudan, LT, SI, proj. lim (2013)'
data_comment = 'Cross-section data for scalar interaction normalised to nucleon'
data_reference = 'Available in SUSY 2013, <a href ="http://susy2013.ictp.it/sessions_timetable.html">Dark Matter and Cosmology Session</a>, <a href ="http://susy2013.ictp.it/lecturenotes/04_Thursday/Dark_Matter_and_Cosmology/Villano.pdf">Talk</a> by A. Villano'
private_comment = ''
data_typeoflimit = ['Exclusion Plot', 'SI-Proj']
formdefault_checked = 'checked'
formdefault_color = 'Blk'
formdefault_style = 'Dot'
data_units = ['GeV', 'cm^2']
data_values = np.array([4.1143, 7.7108e-40, 4.288, 4.5845e-40, 4.4693, 2.9359e-40, 4.6583, 2.0251e-40, 4.8554, 1.346e-40, 5.0609, 9.6354e-41, 5.275, 6.6463e-41, 5.4983, 4.7579e-41, 5.7313, 3.8075e-41, 5.9742, 3.047e-41, 6.2273, 2.4384e-41, 6.4913, 2.0251e-41, 6.7667, 1.7456e-41, 7.0537, 1.5046e-41, 7.3528, 1.2969e-41, 7.6644, 1.0771e-41, 7.9896, 9.2841e-42, 8.3286, 8.3053e-42, 8.682, 7.4296e-42, 9.0504, 6.6463e-42, 9.4344, 5.9456e-42, 9.8347, 5.3187e-42, 10.252, 4.7579e-42, 10.687, 4.2563e-42, 11.1404, 3.8075e-42, 11.6133, 3.535e-42, 12.1063, 3.2819e-42, 12.62, 2.9359e-42, 13.1559, 2.8289e-42, 13.7141, 2.5306e-42, 14.2962, 2.3495e-42, 14.9031, 2.1813e-42, 15.5356, 2.0251e-42, 16.1951, 1.8802e-42, 16.8829, 1.8116e-42, 17.6, 1.8116e-42, 18.3475, 1.7456e-42, 19.1266, 1.6819e-42, 19.9392, 1.6819e-42, 20.7859, 1.6206e-42, 21.6686, 1.5615e-42, 22.5887, 1.5046e-42, 23.5483, 1.5046e-42, 24.5483, 1.4497e-42, 25.5908, 1.3969e-42, 26.678, 1.3969e-42, 27.8113, 1.3969e-42, 28.9928, 1.3969e-42, 30.225, 1.4497e-42, 31.5091, 1.4497e-42, 32.8476, 1.4497e-42, 34.2431, 1.4497e-42, 35.6984, 1.5046e-42, 37.2156, 1.5615e-42, 38.7973, 1.6206e-42, 40.4455, 1.6206e-42, 42.1645, 1.6819e-42, 43.9565, 1.7456e-42, 45.8246, 1.8116e-42, 47.7713, 1.8116e-42, 49.8016, 1.8802e-42, 51.9183, 1.9513e-42, 54.1239, 1.9513e-42, 56.4242, 2.0251e-42, 58.8222, 2.1017e-42, 61.3212, 2.1017e-42, 63.9284, 2.2638e-42, 66.6454, 2.3495e-42, 69.4778, 2.4384e-42, 72.4307, 2.5306e-42, 75.509, 2.6264e-42, 78.7181, 2.7257e-42, 82.0637, 2.8289e-42, 85.5514, 2.9359e-42, 89.1874, 3.047e-42, 92.9778, 3.1623e-42]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
