# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop WARP_0701286_55kev.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'WARP_0701286_55keV.limit'
file_status = 'public'
data_label = 'WARP 2.3L, 96.5 kg-days 55 keV threshold'
data_comment = 'Cross-section data for scalar interaction normalised to \nnucleon'
data_reference = 'Astropart. Phys. 28, 495 (2007), astro-ph/0701286 (no events above 55 keV threshold)'
data_typeoflimit = ['Exclusion Plot', 'SI-Exp']
formdefault_checked = ''
formdefault_color = 'Mag'
formdefault_style = 'Line'
data_units = ['GeV', 'cm^2']
data_values = np.array([18.1904, 9.8199e-41, 21.8063, 2.7013e-41, 26.141, 9.7605e-42, 31.3374, 4.8037e-42, 37.5667, 2.8355e-42, 45.0343, 1.9008e-42, 53.9863, 1.4472e-42, 64.7178, 1.2066e-42, 77.5825, 1.1018e-42, 93.0045, 1.0433e-42, 111.4921, 1.0245e-42, 133.6547, 1.0625e-42, 160.2228, 1.122e-42, 192.0722, 1.2288e-42, 230.2527, 1.3457e-42, 276.0228, 1.5283e-42, 330.8911, 1.7044e-42, 396.6662, 2.0074e-42, 475.5162, 2.2798e-42, 570.0402, 2.685e-42, 683.3539, 3.1053e-42, 819.1922, 3.6573e-42, 982.0328, 4.3074e-42, 1177.2431, 5.073e-42, 1411.2576, 6.1959e-42, 1691.79, 7.2972e-42, 2028.0872, 8.752e-42, 2431.2341, 1.0497e-41, 2914.5193, 1.2589e-41, 3493.8728, 1.4827e-41, 4188.3913, 1.7148e-41, 5020.9674, 2.1328e-41, 6019.0446, 2.558e-41, 7215.5214, 3.0126e-41, 8649.836, 3.5481e-41, 10000.0, 4.2555e-41]).reshape(1, -1)
data_values_rescale = np.array([1, 1]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 220
