# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop XENON100_SI_2010.m
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

file_name = 'XENON100_SI_2010.limit'
file_status = 'public'
data_label = 'XENON100 2010 (161 kg-d)'
data_comment = 'Sigma normalized to WIMP-Nucleon [Yellin Max Gap]'
data_reference = 'arXiv:1005.0380'
private_comment = 'Ported from Brown limit plotter, 23Aug2010'
data_typeoflimit = ['Exclusion Plot', 'SI-Exp']
formdefault_checked = ''
formdefault_color = 'Red'
formdefault_style = 'Line'
data_units = ['GeV', 'cm^2']
data_values_rescale = np.array([1, 1]).reshape(1, -1)
data_values = np.array([5.07351, 3.81229e-40, 5.35334, 2.55769e-40, 5.64859, 1.69934e-40, 5.96013, 1.16251e-40, 6.42536, 6.67445e-41, 6.85293, 4.14242e-41, 7.30895, 2.5961e-41, 7.75358, 1.70816e-41, 8.18121, 1.10224e-41, 8.65564, 7.18217e-42, 9.18219, 4.41435e-42, 10.0596, 2.39066e-42, 10.9326, 1.28215e-42, 12.0095, 6.87643e-43, 13.7345, 3.44502e-43, 15.7386, 1.93827e-43, 18.0674, 1.17508e-43, 20.3359, 8.11284e-44, 22.6039, 6.37871e-44, 25.671, 4.95049e-44, 28.5852, 4.20805e-44, 32.4058, 3.67116e-44, 37.0677, 3.33015e-44, 42.4003, 3.16142e-44, 48.3265, 3.08029e-44, 55.8764, 3.14094e-44, 66.4851, 3.26584e-44, 78.9662, 3.57695e-44, 92.9539, 3.9177e-44, 111.798, 4.51991e-44, 130.895, 5.04796e-44, 154.081, 5.78619e-44, 179.113, 6.58941e-44, 205.985, 7.45552e-44, 236.464, 8.32652e-44, 273.406, 9.54421e-44, 319.537, 1.10831e-43, 369.457, 1.26216e-43, 424.886, 1.45618e-43, 486.882, 1.65832e-43, 556.925, 1.87629e-43, 635.903, 2.15069e-43, 743.197, 2.49746e-43, 833.519, 2.78923e-43, 934.818, 3.1354e-43, 991.771, 3.34596e-43]).reshape(1, -1)
param_halodensity = 0.3
param_halovelocity = 230
