*       Vocabulary for MPI-stub :
      parameter (MPI_COMM_WORLD=0)
      parameter (MPI_INTEGER=15)
      parameter (MPI_REAL=16)
      parameter (MPI_DOUBLE_PRECISION=17)
      parameter (MPI_CHARACTER=20)
      parameter (MPI_PROC_NULL=-1)
      parameter (MPI_ANY_SOURCE=-2)
      parameter (MPI_ANY_TAG=-1)
      parameter (MPI_STATUS_SIZE=8)
      parameter (MPI_SOURCE=1)
      parameter (MPI_TAG=2)
      real*8 MPI_WTIME